server:
  port: 8080
  servlet:
    context-path: /user
spring:
  application:
    name: galaxy-user
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:galaxy;
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: osstem

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka


logging:
  level:
    root: debug
